/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mylife_home_hw_driver_platform_PlatformCalls */

#ifndef _Included_mylife_home_hw_driver_platform_PlatformCalls
#define _Included_mylife_home_hw_driver_platform_PlatformCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    read
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_read
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    write
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_write
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    poll
 * Signature: ([Lmylife/home/hw/driver/platform/PlatformCalls/pollfd;I)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_poll
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    lseek
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_lseek
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     mylife_home_hw_driver_platform_PlatformCalls
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mylife_home_hw_driver_platform_PlatformCalls_strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
